version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "3000:3000"
    environment:
      # These environment variables can be used in your Go app for DB connection.
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: article
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: article
      # PGPORT: 5433
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: