basePath: /
definitions:
  controllers.CreateArticleRequest:
    properties:
      category:
        type: string
      content:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  models.Posts:
    properties:
      category:
        type: string
      content:
        type: string
      createdDate:
        type: string
      id:
        type: integer
      status:
        type: string
      timestamp:
        type: string
      title:
        type: string
      updatedDate:
        type: string
    type: object
host: localhost:3000/api
info:
  contact:
    email: alwi.aldisyach@gmail.com
    name: Alwi Aldiansyach
  description: This is a doc API for backend SV
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: backend SV
  version: "1.0"
paths:
  /article:
    post:
      consumes:
      - application/json
      description: Add article and save to database.
      parameters:
      - description: the body to create a Article
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CreateArticleRequest'
      summary: Add article.
      tags:
      - Article
  /article/:id:
    get:
      consumes:
      - application/json
      description: Get article by Id.
      parameters:
      - description: article id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Posts'
      summary: Get article By ID.
      tags:
      - Article
  /article/:limit/:offset:
    get:
      consumes:
      - application/json
      description: Get article by Limit and offset.
      parameters:
      - description: article limit
        in: path
        name: limit
        required: true
        type: integer
      - description: article offset
        in: path
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Posts'
            type: array
      summary: Get article with limit and offset.
      tags:
      - Article
swagger: "2.0"
