basePath: localhost:3000/api
definitions:
  controllers.ArticleRequest:
    properties:
      category:
        minLength: 3
        type: string
      content:
        minLength: 200
        type: string
      status:
        enum:
        - publish
        - draft
        - thrash
        type: string
      title:
        minLength: 20
        type: string
    required:
    - category
    - content
    - status
    - title
    type: object
host: localhost:3000
info:
  contact:
    email: alwi.aldisyach@gmail.com
    name: Alwi Aldiansyach
  description: This is a doc API for backend SV
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: backend SV
  version: "1.0"
paths:
  /article:
    post:
      consumes:
      - application/json
      description: Add article and save to database.
      parameters:
      - description: the body to create a Article
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Add article.
      tags:
      - Article
  /article/:id:
    delete:
      consumes:
      - application/json
      description: Delete article by Id.
      parameters:
      - description: article id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete article By ID.
      tags:
      - Article
    get:
      consumes:
      - application/json
      description: Get article by Id.
      parameters:
      - description: article id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get article By ID.
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: Edit article by Id.
      parameters:
      - description: article id
        in: path
        name: id
        required: true
        type: string
      - description: the body to update a Article
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Edit article By ID.
      tags:
      - Article
  /article/:status/:limit/:offset:
    get:
      consumes:
      - application/json
      description: Get article by Limit and offset.
      parameters:
      - description: article limit
        in: path
        name: limit
        required: true
        type: integer
      - description: article offset
        in: path
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get article with limit and offset.
      tags:
      - Article
swagger: "2.0"
